/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef storm_CONSTANTS_H
#define storm_CONSTANTS_H

#include "storm_types.h"



class stormConstants {
 public:
  stormConstants();

};

extern const stormConstants g_storm_constants;



#endif
